Feature/comprehend pii
aws-samples/amazon-textract-idp-cdk-constructs pull request #47
Opened 2023-03-10 21:01 UTC by MichaelWalker-git

### Description
- Add Comprehend PII Construct

### Jira ticket:
https://jira.aws-prototyping.cloud/browse/PE789E67CC37-330

2023-03-14 19:38 UTC, schadem requested changes
This does not seem to work

2023-03-14 19:38 UTC, schadem commented on lambda/comprehend_pii_sync/app/requirements.txt
> +amazon-textract-caller
amazon-textract-caller is not used

2023-03-14 19:38 UTC, schadem commented on lambda/comprehend_pii_sync/app/sync_main.py
> +sqs = boto3.client('sqs')
is not used

2023-03-14 19:38 UTC, schadem commented on lambda/comprehend_pii_sync/app/sync_main.py
> +            EndpointArn=comprehend_classifier_arn,
not supported by detect_pii_entities

2023-03-14 19:38 UTC, schadem commented on lambda/comprehend_pii_sync/app/sync_main.py
> +            }
not supported by detect_pii_entities

2023-03-14 19:38 UTC, schadem commented on lambda/comprehend_pii_sync/app/sync_main.py
> +                break
is not a classifier

2023-03-16 20:42 UTC, MichaelWalker-git commented on lambda/comprehend_pii_sync/app/sync_main.py
> +    for c in response['Entities']:
Input: Textract JSON
Output - PII:
- Enhanced Textract json (list of blocks: words and lines)
- Indicate which words are PII
- Remapping using BeginOffset 
-

2023-03-16 21:00 UTC, MichaelWalker-git commented on lambda/comprehend_pii_sync/app/sync_main.py
> +        response = comprehend.detect_pii_entities(
Mark the block as PII. Custom element

2023-03-16 21:00 UTC, MichaelWalker-git commented on lambda/comprehend_pii_sync/app/sync_main.py
> +        send_success_to_step_function(response, token, event, start_time)
All the blocks of textract + information about the offset.

Each words would have an offset.

2023-03-16 21:00 UTC, MichaelWalker-git commented on lambda/comprehend_pii_sync/app/sync_main.py
> +    for c in response['Entities']:
https://github.com/aws-samples/amazon-textract-idp-cdk-constructs/blob/3f40a57261d75c7a37d9a375472c816327fcad93/lambda/generatecsv/app/main.py#L96

2023-03-16 21:00 UTC, MichaelWalker-git commented on lambda/comprehend_pii_sync/app/sync_main.py
> +        send_success_to_step_function(response, token, event, start_time)
https://github.com/aws-samples/amazon-textract-idp-cdk-constructs/blob/3f40a57261d75c7a37d9a375472c816327fcad93/lambda/generatecsv/app/main.py#L96

2023-07-18 20:27 UTC, closed without merging